# Generated by Django 6.0.6 on 2026-07-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('spesialis', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('diagnosa', models.TextField()),
                ('tanggal', models.DateField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pasien')),
            ],
        ),
    ]
